version: "3.8"
services:
  db:
    image: postgres:15
    container_name: currency_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-prod
    ports:
      - 5432:5432

  currency:
    image: currency_app
    build:
      context: .
    container_name: currency_app
    env_file:
      - .env-prod
    depends_on:
      - db
    command: ["/currency/docker/app.sh"]
    ports:
      - 7777:8000

  # prometheus:
  #   image: prom/prometheus:v2.43.0
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheusdata:/prometheus
  #   restart: unless-stopped
  #   ports:
  #     - 9090:9090

  # grafana:
  #   image: grafana/grafana:9.4.7
  #   container_name: grafana
  #   volumes:
  #     - grafanadata:/var/lib/grafana
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
      
volumes:
  postgresdata:
  # grafanadata:
  # prometheusdata: